spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    title: My API
    description: This is a custom description of my API.
    version: 1.0
  swagger-ui:
    enabled: true